### ISSUE TITLE
node环境添加notabase模块运行不起来

### ISSUE THREAD

**Issue by itribs** [cyanzhong/jsbox-issues#14]
let Notabase = require("notabase");

在pc端试了没问题，在jsbox下报以下错误：

{ SyntaxError: Expected identifier, string or number
at Script (vm.js:87:7)
at createScript (vm.js:251:3)
at runInThisContext (vm.js:303:3)
at Module.prototype.compile (internal/modules/cjs/loader.js:656:3)
at Module.extensions[.js] (internal/modules/cjs/loader.js:699:3)
at Module.prototype.load (internal/modules/cjs/loader.js:598:3)
at tryModuleLoad (internal/modules/cjs/loader.js:537:5)
at Module.load (internal/modules/cjs/loader.js:529:3)
at Module.prototype.require (internal/modules/cjs/loader.js:636:3)
at require (internal/modules/cjs/helpers.js:20:7)
at Anonymous function (/private/var/mobile/Containers/Shared/AppGroup/A328CB64-D905-4734-AEDF-129FFA43D077/JSBox/Code/NodeModule/index.js:1:63)
at Module.prototype.compile (internal/modules/cjs/loader.js:688:5)
at Module.extensions[.js] (internal/modules/cjs/loader.js:699:3)
at Module.prototype.load (internal/modules/cjs/loader.js:598:3)
at tryModuleLoad (internal/modules/cjs/loader.js:537:5)
at Module.load (internal/modules/cjs/loader.js:529:3)
at Module.prototype.require (internal/modules/cjs/loader.js:636:3)
at require (internal/modules/cjs/helpers.js:20:7)
at Anonymous function (/private/var/mobile/Containers/Data/Application/5ECC1F71-C56B-4192-B0A5-E6171B7C49D9/Documents/nodeFiles/ed72c809bc40457dddc617fd1adc8ffc.node.js:10:295)
at Domain.prototype.run (domain.js:343:5)
at Anonymous function (/private/var/mobile/Containers/Data/Application/5ECC1F71-C56B-4192-B0A5-E6171B7C49D9/Documents/nodeFiles/ed72c809bc40457dddc617fd1adc8ffc.node.js:10:269)
at Module.prototype.compile (internal/modules/cjs/loader.js:688:5)
at Module.extensions[.js] (internal/modules/cjs/loader.js:699:3)
at Module.prototype.load (internal/modules/cjs/loader.js:598:3)
at tryModuleLoad (internal/modules/cjs/loader.js:537:5)
at Module.load (internal/modules/cjs/loader.js:529:3)
at Module.prototype.require (internal/modules/cjs/loader.js:636:3)
at require (internal/modules/cjs/helpers.js:20:7)
at Global code (repl:1:181)
at sigintHandlersWrap (vm.js:262:5)
at Script.prototype.runInContext (vm.js:104:7)
at defaultEval (repl.js:331:13)
at bound (domain.js:396:5)
at runBound (domain.js:409:5)
at onLine (repl.js:642:5)
at Reflect.apply (native code)
at emit (events.js:182:5)
at Reflect.apply (native code)
at EventEmitter.prototype.emit (domain.js:442:5)
at Interface.prototype.onLine (readline.js:290:5)
description: 'Expected identifier, string or number',
message: 'Expected identifier, string or number',
line: 55,
column: 32,
length: 3,
source: ' ...tkHeader',
url:
'/private/var/mobile/Containers/Shared/AppGroup/A328CB64-D905-4734-AEDF-129FFA43D077/JSBox/Code/NodeModule/node_modules/notabase/src/notabase.js' }

**Comment by cyanzhong** [comment]
我估计它使用了 {...object} 语法，不支持在 Node.js 10 上面运行，你可以尝试用 babel + webpack 打包这个项目。

**Comment by cyanzhong** [comment]
@itribs `Build 636` 支持了这个 syntax

**Comment by itribs** [comment]
> @itribs `Build 636` 支持了这个 syntax

谢谢
